---
title: "Unveiling Hidden Patterns: Clustering Analysis with ISMIP6 Models"
author: Eleanor M. Byrne
subtitle: A PCA and Clustering Analysis 
date: today
date-format: long
---

# Introduction

How do different Global Climate Models (GCMs) impact the projections of ice sheet behavior in ISMIP6 simulations? What is the influence of ocean forcing on the projections of ice sheet dynamics in ISMIP6 models? How do different Representative Concentration Pathways (RCPs) affect the projected outcomes of ice sheet models in ISMIP6? These are questions that have been asked within the ice sheet community in the recent years as new data, methods, and ideas have been discovered.

The Ice Sheet Model Intercomparison Project for CMIP6 (ISMIP6) aims to address these questions by providing a framework for evaluating and comparing the responses of ice sheet models to various climate scenarios. ISMIP6 integrates multiple GCMs, RCPs, and ocean forcing parameters to project the future behavior of the Greenland and Antarctic ice sheets.

This study focuses on analyzing the RCP experiments and looking at one key variable Surface Mass Balance flux (acabf). Principal Component Analysis (PCA) and K-means clustering will be used to analyze the variables, aiming to uncover patterns and groupings in the data. **Hypothesis:** By implementing PCA and Clustering methods,it is possible to uncover hidden patterns in the ISMIP6 simulation data, enabling more efficient data reduction and grouping of similar data points for further analysis. This approach will help to understand the variations in ice sheet response under various scenarios, RCP 8.5 and 2.6.

# Materials and methods

Narrative:

Code:

As the code was extensive, there wasn't an option for running the code in the qmd folder as a data processing was on a larger scale. Instead the code has been broken into multiple script each serving a purpose.

-   file_script.R = For setting up the variables, experiment types, and to assign the date

-   data_extraction.R = Extracting the variable data based on the date (2015).

-   Clean_data.R = To flatten the data points and then convert zero to NaN and drop across all models.

-   PCA_script.R = To standardize the data points and to impliment the PCA. This also contains plots for visualizations.

-   Kmeans_clust.R = To impliment the k-means clustering from the reduced data points from the PCA. Contains plots for the visualizations.

Data:

The data used in this study was sourced from the Center for Computational Research (CCR) at the University at Buffalo. The ISMIP6 dataset was previously downloaded from the CCR repository, focusing on the experiment and variable types needed for the RCP experiment group. This dataset includes projections of land ice thickness different Representative Concentration Pathways (RCPs). More information for ISMIP6 and the CCR can be found at:

[GHub Link](%22https://theghub.org/groups/ismip6/wiki%22)

[CCR website](https://www.buffalo.edu/ccr.html)

The file format of the ISMIP6 folders is *\<variable\>\_\<IS\>\_\<GROUP\>\_\<MODEL\>\_\<EXP\>.nc*

Variable = SMB, IS is either Greenland (GIS) or Antarctica (AIS), with the model names and groups, along with the experiment types 05 & 07 (RCP8.5 and RCP2.6).

# Load any required packages in a code chunk (you may need to install some packages):

```{r, message=F, warning=F}
# loading needed packages 
# install.packages("tidyverse")
library(tidyverse)
library(leaflet)
library(kableExtra)
library(htmlwidgets)
library(widgetframe)
library(lattice)
library(ncdf4)
library(stringr)
library(dplyr)
library(rmarkdown)
library(knitr)
library(curl)
# install.packages("corrr")
library('corrr')
# install.packages("FactoMineR")
library("FactoMineR")
# install.packages("ggcorrplot")
library(ggcorrplot)
knitr::opts_chunk$set(widgetframe_widgets_dir = 'widgets' ) 
knitr::opts_chunk$set(cache=TRUE)  # cache the results for quick compiling
```

# Results

\[\~200 words\]

Tables and figures (maps and other graphics) are carefully planned to convey the results of your analysis. Intense exploration and evidence of many trials and failures. The author looked at the data in many different ways before coming to the final presentation of the data.

Show tables, plots, etc. and describe them.

### Dygraphs Example

# Conclusions

\[\~200 words\]

Clear summary adequately describing the results and putting them in context. Discussion of further questions and ways to continue investigation.

# References

All sources are cited in a consistent manner
